<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>RAPIDA Export Summary</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #1e293b; line-height: 1.5; }
        .header { background-color: #1a3a4a; color: #ffffff; padding: 24px 32px; }
        .header h1 { font-size: 22px; margin-bottom: 4px; }
        .header p { font-size: 11px; opacity: 0.85; }
        .content { padding: 24px 32px; }
        .section { margin-bottom: 24px; }
        .section h2 { font-size: 15px; color: #1a3a4a; border-bottom: 2px solid #1a3a4a; padding-bottom: 6px; margin-bottom: 12px; }
        .meta-row { margin-bottom: 6px; }
        .meta-label { font-weight: bold; display: inline-block; width: 120px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; }
        th { background-color: #f1f5f9; font-weight: bold; color: #1a3a4a; }
        td { background-color: #ffffff; }
        .stats-table td:last-child { text-align: right; font-weight: bold; }
        .footer { margin-top: 32px; padding: 16px 32px; border-top: 1px solid #cbd5e1; text-align: center; font-size: 10px; color: #64748b; }
    </style>
</head>
<body>
    <div class="header">
        <h1>RAPIDA Crisis Report Summary</h1>
        <p>{{ $crisis->name }}</p>
    </div>

    <div class="content">
        <div class="section">
            <h2>Overview</h2>
            <div class="meta-row">
                <span class="meta-label">Crisis:</span>
                <span>{{ $crisis->name }}</span>
            </div>
            <div class="meta-row">
                <span class="meta-label">Date Range:</span>
                <span>{{ $dateRange['start'] ?? 'N/A' }} &mdash; {{ $dateRange['end'] ?? 'N/A' }}</span>
            </div>
            <div class="meta-row">
                <span class="meta-label">Total Reports:</span>
                <span>{{ $totalReports }}</span>
            </div>
        </div>

        <div class="section">
            <h2>Damage Breakdown</h2>
            <table class="stats-table">
                <thead>
                    <tr>
                        <th>Category</th>
                        <th>Count</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Total Reports</td>
                        <td>{{ $totalReports }}</td>
                    </tr>
                    <tr>
                        <td>Minimal Damage</td>
                        <td>{{ $damageBreakdown['minimal'] }}</td>
                    </tr>
                    <tr>
                        <td>Partial Damage</td>
                        <td>{{ $damageBreakdown['partial'] }}</td>
                    </tr>
                    <tr>
                        <td>Complete Damage</td>
                        <td>{{ $damageBreakdown['complete'] }}</td>
                    </tr>
                </tbody>
            </table>
        </div>

        @if($topH3Cells->isNotEmpty())
        <div class="section">
            <h2>Top Reported Areas (H3 Cells)</h2>
            <table>
                <thead>
                    <tr>
                        <th>H3 Cell ID</th>
                        <th>Report Count</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($topH3Cells as $cellId => $count)
                    <tr>
                        <td>{{ $cellId }}</td>
                        <td>{{ $count }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @endif
    </div>

    <div class="footer">
        Generated by RAPIDA &mdash; UNDP Crisis Mapping | {{ now()->format('Y-m-d H:i:s') }} UTC
    </div>
</body>
</html>
